export const movies = [
  {
    adult: false,
    backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
    genre_ids: [16, 12, 10751, 35],
    id: 1241982,
    original_language: "en",
    original_title: "Moana 2",
    overview:
      "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
    popularity: 5883.763,
    poster_path: "/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg",
    release_date: "2024-11-27",
    title: "Moana 2",
    video: false,
    vote_average: 7,
    vote_count: 320,
  },
  {
    adult: false,
    backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
    genre_ids: [878, 28, 12],
    id: 912649,
    original_language: "en",
    original_title: "Venom: The Last Dance",
    overview:
      "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    popularity: 3523.453,
    poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
    release_date: "2024-10-22",
    title: "Venom: The Last Dance",
    video: false,
    vote_average: 6.4,
    vote_count: 986,
  },
  {
    adult: false,
    backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
    genre_ids: [28, 878, 53],
    id: 1035048,
    original_language: "en",
    original_title: "Elevation",
    overview:
      "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
    popularity: 2204.744,
    poster_path: "/uQhYBxOVFU6s9agD49FnGHwJqG5.jpg",
    release_date: "2024-11-07",
    title: "Elevation",
    video: false,
    vote_average: 6.4,
    vote_count: 87,
  },
  {
    adult: false,
    backdrop_path: "/6lE2e6j8qbtQR8aHxQNJlwxdmKV.jpg",
    genre_ids: [28, 80, 53],
    id: 974453,
    original_language: "en",
    original_title: "Absolution",
    overview:
      "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
    popularity: 1777.824,
    poster_path: "/cNtAslrDhk1i3IOZ16vF7df6lMy.jpg",
    release_date: "2024-10-31",
    title: "Absolution",
    video: false,
    vote_average: 6.1,
    vote_count: 103,
  },
  {
    adult: false,
    backdrop_path: "/evFChfYeD2LqobEJf8iQsrYcGTw.jpg",
    genre_ids: [28, 80, 53],
    id: 1182387,
    original_language: "en",
    original_title: "Armor",
    overview:
      "Armored truck security guard James Brody is working with his son Casey transporting millions of dollars between banks when a team of thieves led by Rook orchestrate a takeover of their truck to seize the riches. Following a violent car chase, Rook soon has the armored truck surrounded and James and Casey find themselves cornered onto a decrepit bridge.",
    popularity: 1686.649,
    poster_path: "/pnXLFioDeftqjlCVlRmXvIdMsdP.jpg",
    release_date: "2024-10-30",
    title: "Armor",
    video: false,
    vote_average: 5.5,
    vote_count: 43,
  },
  {
    adult: false,
    backdrop_path: "/h3fwlwHotd3JfV13HdW0mxDcxPD.jpg",
    genre_ids: [35, 10749, 10770],
    id: 957119,
    original_language: "en",
    original_title: "Sidelined: The QB and Me",
    overview:
      "Dallas, a burdened but headstrong dancer, is determined to get into the best dance school in the country—her late mother’s alma mater. However, that dream is suddenly derailed when the cheeky yet secretly grieving football star, Drayton, crashes into her life with a unique story of his own. Will the two of them be able to grow into their dreams together, or will their dreams be sidelined?",
    popularity: 1605.297,
    poster_path: "/sIWv5HtDlUFvacsuA1fRNWZ5GFH.jpg",
    release_date: "2024-11-29",
    title: "Sidelined: The QB and Me",
    video: false,
    vote_average: 6.5,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    genre_ids: [28, 12, 36],
    id: 558449,
    original_language: "en",
    original_title: "Gladiator II",
    overview:
      "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
    popularity: 1244.766,
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    release_date: "2024-11-13",
    title: "Gladiator II",
    video: false,
    vote_average: 6.7,
    vote_count: 924,
  },
  {
    adult: false,
    backdrop_path: "/mQZJoIhTEkNhCYAqcHrQqhENLdu.jpg",
    genre_ids: [16, 878, 10751],
    id: 1184918,
    original_language: "en",
    original_title: "The Wild Robot",
    overview:
      "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    popularity: 1190.606,
    poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
    release_date: "2024-09-12",
    title: "The Wild Robot",
    video: false,
    vote_average: 8.4,
    vote_count: 3293,
  },
  {
    adult: false,
    backdrop_path: "/iqvwqusm7gNP26SxbmwHXOkYFFF.jpg",
    genre_ids: [18, 10749],
    id: 179387,
    original_language: "tl",
    original_title: "Heavenly Touch",
    overview:
      "Jonard is having trouble making ends meet. His mother is suffering from depression, and he and his sister are forced to quit school in order to take care of her. One day, Jonard meets up his friend Rodel, and Rodel introduces him to the world of massage parlors. Rodel teaches him massage, and brings him to Heavenly Touch, a syndicate-run massage parlor that mostly caters to homosexuals.",
    popularity: 1067.077,
    poster_path: "/ory8WuAqznTE7lfopTSymHpop2t.jpg",
    release_date: "2009-05-12",
    title: "Heavenly Touch",
    video: false,
    vote_average: 6.1,
    vote_count: 27,
  },
  {
    adult: false,
    backdrop_path: "/iR79ciqhtaZ9BE7YFA1HpCHQgX4.jpg",
    genre_ids: [27, 9648],
    id: 1100782,
    original_language: "en",
    original_title: "Smile 2",
    overview:
      "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.",
    popularity: 1052.521,
    poster_path: "/ht8Uv9QPv9y7K0RvUyJIaXOZTfd.jpg",
    release_date: "2024-10-16",
    title: "Smile 2",
    video: false,
    vote_average: 6.6,
    vote_count: 825,
  },
  {
    adult: false,
    backdrop_path: "/bbNUSVOqgbJ2U5OtEeMC76qlqxH.jpg",
    genre_ids: [18, 14, 10749],
    id: 402431,
    original_language: "en",
    original_title: "Wicked",
    overview:
      "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
    popularity: 987.814,
    poster_path: "/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
    release_date: "2024-11-20",
    title: "Wicked",
    video: false,
    vote_average: 7.6,
    vote_count: 398,
  },
  {
    adult: false,
    backdrop_path: "/fSSCsemHjUJzLrr3Trp72Oa5Dj0.jpg",
    genre_ids: [16, 9648, 878, 28],
    id: 1299652,
    original_language: "en",
    original_title: "Watchmen: Chapter II",
    overview:
      "Suspicious of the events ensnaring their former colleagues, Nite Owl and Silk Spectre are spurred out of retirement to investigate. As they grapple with personal ethics, inner demons and a society turned against them, they race the clock to uncover a deepening plot that might trigger global nuclear war.",
    popularity: 924.906,
    poster_path: "/4rBObJFpiWJOG7aIlRrOUniAkBs.jpg",
    release_date: "2024-11-25",
    title: "Watchmen: Chapter II",
    video: false,
    vote_average: 7.2,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/dvBCdCohwWbsP5qAaglOXagDMtk.jpg",
    genre_ids: [28, 35, 878],
    id: 533535,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    popularity: 893.462,
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    release_date: "2024-07-24",
    title: "Deadpool & Wolverine",
    video: false,
    vote_average: 7.679,
    vote_count: 5771,
  },
  {
    adult: false,
    backdrop_path: "/liuBLPXvisMRo5w2JEKHXceWq5u.jpg",
    genre_ids: [28, 80, 18],
    id: 1171640,
    original_language: "fr",
    original_title: "GTMAX",
    overview:
      "When a notorious gang of bikers recruits her brother for a heist, a former motocross champion must face her deepest fears to keep her family safe.",
    popularity: 889.427,
    poster_path: "/bx92hl70NUhojjO3eV6LqKllj4L.jpg",
    release_date: "2024-11-19",
    title: "GTMAX",
    video: false,
    vote_average: 6,
    vote_count: 66,
  },
  {
    adult: false,
    backdrop_path: "/18TSJF1WLA4CkymvVUcKDBwUJ9F.jpg",
    genre_ids: [27, 53],
    id: 1034541,
    original_language: "en",
    original_title: "Terrifier 3",
    overview:
      "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
    popularity: 875.785,
    poster_path: "/63xYQj1BwRFielxsBDXvHIJyXVm.jpg",
    release_date: "2024-10-09",
    title: "Terrifier 3",
    video: false,
    vote_average: 6.9,
    vote_count: 1178,
  },
  {
    adult: false,
    backdrop_path: "/2fxnTXr8NwyTFkunkimJkGkhqfy.jpg",
    genre_ids: [18, 28, 27],
    id: 1118031,
    original_language: "es",
    original_title: "Apocalipsis Z: el principio del fin",
    overview:
      "When a kind of rabies that transforms people into aggressive creatures spreads across the planet, Manel isolates himself at home with his cat, relying on his wits to survive; but soon they must go out in search of food, by land and by sea, dodging many dangers.",
    popularity: 855.638,
    poster_path: "/wIGJnIFQlESkC2rLpfA8EDHqk4g.jpg",
    release_date: "2024-10-04",
    title: "Apocalypse Z: The Beginning of the End",
    video: false,
    vote_average: 6.848,
    vote_count: 650,
  },
  {
    adult: false,
    backdrop_path: "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
    genre_ids: [27, 878, 53],
    id: 933260,
    original_language: "en",
    original_title: "The Substance",
    overview:
      "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    popularity: 781.502,
    poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    release_date: "2024-09-07",
    title: "The Substance",
    video: false,
    vote_average: 7.265,
    vote_count: 2373,
  },
  {
    adult: false,
    backdrop_path: "/6vn6K9oX82i6E86ZiHVxqVEMQqP.jpg",
    genre_ids: [27, 878],
    id: 945961,
    original_language: "en",
    original_title: "Alien: Romulus",
    overview:
      "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    popularity: 767.105,
    poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    release_date: "2024-08-13",
    title: "Alien: Romulus",
    video: false,
    vote_average: 7.2,
    vote_count: 2529,
  },
  {
    adult: false,
    backdrop_path: "/rOmUuQEZfPXglwFs5ELLLUDKodL.jpg",
    genre_ids: [28, 35, 14],
    id: 845781,
    original_language: "en",
    original_title: "Red One",
    overview:
      "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous bounty hunter in a globe-trotting, action-packed mission to save Christmas.",
    popularity: 743.214,
    poster_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
    release_date: "2024-10-31",
    title: "Red One",
    video: false,
    vote_average: 6.6,
    vote_count: 208,
  },
  {
    adult: false,
    backdrop_path: "/5O0mkQGfOQM4OktFOCep9YmXK79.jpg",
    genre_ids: [28, 878, 53, 35, 27],
    id: 995803,
    original_language: "en",
    original_title: "Arena Wars",
    overview:
      "In 2045 convicted criminals are given the opportunity to compete on the world's #1 televised sporting event, Arena Wars. They must survive 7 rooms and 7 of the most vicious killers in the country. If they win, they regain their freedom.",
    popularity: 682.657,
    poster_path: "/4dRtXjk1rcsZlaMJpBn6Nh9cTfO.jpg",
    release_date: "2024-06-25",
    title: "Arena Wars",
    video: false,
    vote_average: 5.463,
    vote_count: 27,
  },
];

// export const movies = [
//     {
//       "adult": false,
//       "backdrop_path": "/AhBxEuJsd4n4FLCebPzLq0IMjrp.jpg",
//       "genre_ids": [18, 9648, 28],
//       "id": 1316205,
//       "original_language": "zh",
//       "original_title": "狄仁杰·通天人偶",
//       "overview": "After occurrences of a bizarre fire in Luoyang palace, incredible puppetry skills, the Kunlun sacred tree that has been frozen for a thousand years, a shocking bloodthirsty murder case, Wu Zetian's mysterious Plum Blossom Shadow Guard... suddenly two Wu Zetians appear in the world at the same time, and a series of unsolved and intertwined cases emerge. Watch how Di Renjie peels off the layers to uncover the hidden shocking conspiracy.",
//       "popularity": 18.137,
//       "poster_path": "/5kdQMjPzUaH3Q3T00MUEaGAzzaG.jpg",
//       "release_date": "2024-07-13",
//       "title": "The Mystery of Humanoid Puppet",
//       "video": false,
//       "vote_average": 0,
//       "vote_count": 0
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/fh022Zgyoq1UzxshTObNLjQ2JoC.jpg",
//       "genre_ids": [99],
//       "id": 1232289,
//       "original_language": "es",
//       "original_title": "La sociedad de la nieve: ¿Quiénes fuimos en la montaña?",
//       "overview": "An in-depth look at the creative process behind \"Society of the Snow,\" featuring cast, crew, director J.A. Bayona and even real-life survivors.",
//       "popularity": 12.652,
//       "poster_path": "/uHTQVdJHbPMvaOdzqlqBXFTctCp.jpg",
//       "release_date": "2024-01-23",
//       "title": "Society of the Snow: Who Were We on the Mountain?",
//       "video": false,
//       "vote_average": 7.3,
//       "vote_count": 53
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/przsU4aiGsdlDkCp5uV8kq8gbLe.jpg",
//       "genre_ids": [878, 27, 53],
//       "id": 10384,
//       "original_language": "en",
//       "original_title": "Supernova",
//       "overview": "Set in the 22nd century, when a battered salvage ship sends out a distress signal, the seasoned crew of the rescue hospital ship Nova-17 responds. What they find is a black hole--that threatens to destroy both ships--and a mysterious survivor whose body quickly mutates into a monstrous and deadly form.",
//       "popularity": 16.501,
//       "poster_path": "/AmHGUjhgXnOYRYrF2ZYMtzfwxPe.jpg",
//       "release_date": "2000-01-14",
//       "title": "Supernova",
//       "video": false,
//       "vote_average": 4.9,
//       "vote_count": 381
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/mnHPVOgNfzyfsXFClVi1NCeQvCy.jpg",
//       "genre_ids": [35, 10751, 12],
//       "id": 15489,
//       "original_language": "en",
//       "original_title": "Snow Day",
//       "overview": "When an entire town in upstate New York is closed down by an unexpected snowfall, a \"snow day\" begins when a group of elementary school kids, led by Natalie Brandston, try to ensure that the schools stay closed by stopping a mechanical snowplow driver by trying to hijack his plow truck. Meanwhile, Natalie's big brother Hal is using this day to try to win the affections of Claire Bonner, the most popular girl in his high school, while Hal and Natalie's father Tom, a TV meteorologist, faces off against a rival meteorologist for weather coverage of the day's events.",
//       "popularity": 8.501,
//       "poster_path": "/myTnHKy178rrd1oUG3GkEvc641G.jpg",
//       "release_date": "2000-02-11",
//       "title": "Snow Day",
//       "video": false,
//       "vote_average": 5.1,
//       "vote_count": 205
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/o4UvkrkSQBjxgyOKVvFOrdYToxx.jpg",
//       "genre_ids": [80, 10749, 18],
//       "id": 10810,
//       "original_language": "es",
//       "original_title": "Rosario Tijeras",
//       "overview": "Rosario Tijeras has been abused by men all her life, initially by her stepfather. Years later, she works as a paid assassin, seducing men and killing them when they least expect it. She meets Emilio, a wealthy womanizer, and his best friend, Antonio, at a nightclub, and starts an affair with Emilio despite Antonio's growing feelings for her. But circumstances bring her closer to Antonio, until her past catches up with her in a devastating way.",
//       "popularity": 14.201,
//       "poster_path": "/d8CnXqN257vDOwZyIaA0IM6DcoU.jpg",
//       "release_date": "2005-08-12",
//       "title": "Rosario Tijeras",
//       "video": false,
//       "vote_average": 6.6,
//       "vote_count": 90
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/t31mKP1dIzUiy0yapCje0vdf2ZY.jpg",
//       "genre_ids": [80, 18],
//       "id": 1429,
//       "original_language": "en",
//       "original_title": "25th Hour",
//       "overview": "In New York City in the days following the events of 9/11, Monty Brogan is a convicted drug dealer about to start a seven-year prison sentence, and his final hours of freedom are devoted to hanging out with his closest buddies and trying to prepare his girlfriend for his extended absence.",
//       "popularity": 18.001,
//       "poster_path": "/uW7tTRElr2tRhmAVESzvHy4ByXg.jpg",
//       "release_date": "2002-12-19",
//       "title": "25th Hour",
//       "video": false,
//       "vote_average": 7.326,
//       "vote_count": 2336
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/iNfDwioDBzqodomLbMfV8ZXj0yL.jpg",
//       "genre_ids": [53, 878, 28, 80],
//       "id": 8831,
//       "original_language": "en",
//       "original_title": "Timecop",
//       "overview": "An officer for a security agency that regulates time travel, must fend for his life against a shady politician who has a tie to his past.",
//       "popularity": 14,
//       "poster_path": "/bgxP6ws8ErBiarnb4S93vv0lkf4.jpg",
//       "release_date": "1994-09-15",
//       "title": "Timecop",
//       "video": false,
//       "vote_average": 6.002,
//       "vote_count": 1151
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/epWLmnK6XYtlR8ICOKauGH546W2.jpg",
//       "genre_ids": [16, 12, 10402],
//       "id": 14906,
//       "original_language": "en",
//       "original_title": "Saludos Amigos",
//       "overview": "A whimsical blend of live action and animation, \"Saludos Amigos\" is a colorful kaleidoscope of art, adventure and music set to a toe-tapping samba beat. From high Andes peaks and Argentina's pampas to the sights and sounds of Rio de Janeiro, your international traveling companions are none other than those famous funny friends, Donald Duck and Goofy. They keep things lively as Donald encounters a stubborn llama and \"El Gaucho\" Goofy tries on the cowboy way of life....South American-style.",
//       "popularity": 15.5,
//       "poster_path": "/kdZyHjsSHYBO53o59ZMz4fOXcmk.jpg",
//       "release_date": "1942-08-24",
//       "title": "Saludos Amigos",
//       "video": false,
//       "vote_average": 5.818,
//       "vote_count": 462
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/cL0GxrBnjgWV381C1NLroeNUcTn.jpg",
//       "genre_ids": [35, 18, 10749],
//       "id": 14736,
//       "original_language": "en",
//       "original_title": "Love & Basketball",
//       "overview": "Monica Wright and Quincy McCall grew up in the same neighborhood and have known each other since childhood. As they grow into adulthood, they fall in love, but they also share another all-consuming passion: basketball.  As Quincy and Monica struggle to make their relationship work, they follow separate career paths though high school and college basketball and, they hope, into stardom in big-league professional ball.",
//       "popularity": 13,
//       "poster_path": "/zNZWNX19FZ5QyedprVM0ldsXFiP.jpg",
//       "release_date": "2000-04-21",
//       "title": "Love & Basketball",
//       "video": false,
//       "vote_average": 7.407,
//       "vote_count": 425
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/jgnfSyrtonk5U2UMP7MLtgX2eYt.jpg",
//       "genre_ids": [28, 53],
//       "id": 6058,
//       "original_language": "en",
//       "original_title": "The Patriot",
//       "overview": "A deadly virus threatens to wipe out an entire Rocky Mountain town, leaving the town doctor to find some way to escape the soldiers who enforce the town's quarantine and devise an antidote. Matters take a more deadly turn after the physician is captured by a dangerously unstable band of militia extremists.",
//       "popularity": 7.997,
//       "poster_path": "/5lmW1yBXAHkOc533wRDEqp3jlCV.jpg",
//       "release_date": "1998-07-10",
//       "title": "The Patriot",
//       "video": false,
//       "vote_average": 5.7,
//       "vote_count": 365
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/FtrwfLziRMeZMMyUEquHs81JMV.jpg",
//       "genre_ids": [27, 80, 53],
//       "id": 326446,
//       "original_language": "en",
//       "original_title": "Savageland",
//       "overview": "When a small town near the Arizona-Mexico border is wiped out overnight, suspicion falls on the lone survivor. But a roll of photos the survivor took that night tells a different story.",
//       "popularity": 11.594,
//       "poster_path": "/7updnUGOoeQx9TWxqGxiNLFODam.jpg",
//       "release_date": "2015-11-01",
//       "title": "Savageland",
//       "video": false,
//       "vote_average": 6.8,
//       "vote_count": 78
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/27NS2ZLNlu5WuN7vVeekLEYAYjX.jpg",
//       "genre_ids": [18],
//       "id": 668333,
//       "original_language": "ja",
//       "original_title": "ワイセツな女　黒い肌に泣く",
//       "overview": "A married couple, Fumio Asakura and Kumiko, enjoyed having pleasure in each other by taking pictures during sex. Kumiko met her old friend from school, Fuko because her husband went on a business trip for three days. They go to a disco in Tachikawa and are almost attacked by three young Japanese. Fuko calls on a black man named Bill, who lives close to Kumiko...",
//       "popularity": 7.996,
//       "poster_path": "/sUGsjv6hvIA1OEQmJRveWtG41Tq.jpg",
//       "release_date": "1985-03-23",
//       "title": "Waisetsuna onna: kuroi hada ni naku",
//       "video": false,
//       "vote_average": 10,
//       "vote_count": 2
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/auPhV7cBaQH1j0kj4qd1VDe6rCE.jpg",
//       "genre_ids": [35, 18, 10749],
//       "id": 11191,
//       "original_language": "en",
//       "original_title": "Mystic Pizza",
//       "overview": "Three teenage girls come of age while working at a pizza parlor in Mystic, Connecticut.",
//       "popularity": 14.749,
//       "poster_path": "/bV3MvnUTgKlbGi7K1QaYNLhdOlM.jpg",
//       "release_date": "1988-10-13",
//       "title": "Mystic Pizza",
//       "video": false,
//       "vote_average": 6.3,
//       "vote_count": 506
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/6Bgd7xihK37b98ERPTvLOqQO1eu.jpg",
//       "genre_ids": [99],
//       "id": 1005031,
//       "original_language": "en",
//       "original_title": "A Trip to Infinity",
//       "overview": "Does infinity exist? Can we experience the Infinite? In an animated film (created by artists from 10 countries) the world's most cutting-edge scientists and mathematicians go in search of the infinite and its mind-bending implications for the universe.  Eminent mathematicians, particle physicists and cosmologists dive into infinity and its mind-bending implications for the universe.",
//       "popularity": 11.773,
//       "poster_path": "/24EXccaDuDEMYp7eVvsCicj5K41.jpg",
//       "release_date": "2022-09-26",
//       "title": "A Trip to Infinity",
//       "video": false,
//       "vote_average": 7.2,
//       "vote_count": 110
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/8DJQ9NbCtvhMwlh6loabpAraBUt.jpg",
//       "genre_ids": [37],
//       "id": 206633,
//       "original_language": "it",
//       "original_title": "Vendo cara la pelle",
//       "overview": "Shane’s a man come home to settle something he’d tried to forget, but has kept eating at him. His mother, father, and little sister, had been murdered for their land. Specifically an old mine the father had been working at for years with little result, but had finally struck a vein.",
//       "popularity": 8.18,
//       "poster_path": "/4XhEGFXrAw94flUBQRxoJ67jXsz.jpg",
//       "release_date": "1968-05-16",
//       "title": "I'll Sell My Skin Dearly",
//       "video": false,
//       "vote_average": 5.2,
//       "vote_count": 6
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/5bTNiANIo2dXdMFaAvsWRgwgAuq.jpg",
//       "genre_ids": [10751, 14, 35],
//       "id": 2284,
//       "original_language": "en",
//       "original_title": "Mr. Magorium's Wonder Emporium",
//       "overview": "Molly Mahoney is the awkward and insecure manager of Mr. Magorium's Wonder Emporium—the strangest, most fantastic and most wonderful toy store in the world. After Mr. Magorium bequeaths the store to her, a dark and ominous change begins to take over the once-remarkable Emporium.",
//       "popularity": 14.001,
//       "poster_path": "/rdFgWATSVhhFtNYZUFsGcHzltcG.jpg",
//       "release_date": "2007-11-14",
//       "title": "Mr. Magorium's Wonder Emporium",
//       "video": false,
//       "vote_average": 6.239,
//       "vote_count": 1238
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/sAiTihJ8bjEqg8nYUIlTQUnVXuj.jpg",
//       "genre_ids": [37, 12],
//       "id": 2023,
//       "original_language": "en",
//       "original_title": "Hidalgo",
//       "overview": "Set in 1890, this is the story of a Pony Express courier who travels to Arabia to compete with his horse, Hidalgo, in a dangerous race for a massive contest prize, in an adventure that sends the pair around the world...",
//       "popularity": 15.25,
//       "poster_path": "/iGzENlBPYJEFWZnye4t3nqWSSp1.jpg",
//       "release_date": "2004-02-04",
//       "title": "Hidalgo",
//       "video": false,
//       "vote_average": 6.9,
//       "vote_count": 1205
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/rbA4CkeT2ag0RksiIbHSlQnqZRv.jpg",
//       "genre_ids": [14],
//       "id": 300803,
//       "original_language": "en",
//       "original_title": "Dragonheart 3: The Sorcerer's Curse",
//       "overview": "When aspiring knight Gareth goes in search of a fallen comet rumored to contain gold, he is shocked to instead find the dragon Drago. After Drago saves Gareth's life the two become intricately bonded, and must work together to defeat an evil sorcerer and stop his reign of terror. Along the way, Gareth learns the true meaning of being a knight in this fantasy action-adventure for the ages.",
//       "popularity": 16.753,
//       "poster_path": "/mN6B5ITOFelW7OhR7tGd51VhXmH.jpg",
//       "release_date": "2015-02-24",
//       "title": "Dragonheart 3: The Sorcerer's Curse",
//       "video": false,
//       "vote_average": 5.4,
//       "vote_count": 240
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/4EwtIIcqvQzOpqDkWj9vhtmRUQM.jpg",
//       "genre_ids": [28, 12, 80, 53],
//       "id": 9691,
//       "original_language": "en",
//       "original_title": "Assassins",
//       "overview": "Assassin Robert Rath arrives at a funeral to kill a prominent mobster, only to witness a rival hired gun complete the job for him -- with grisly results. Horrified by the murder of innocent bystanders, Rath decides to take one last job and then return to civilian life. But finding his way out of the world of contract killing grows ever more dangerous as Rath falls for his female target and becomes a marked man himself.",
//       "popularity": 13.248,
//       "poster_path": "/kgqS4jn60E8UIExfceMUExB3ZKK.jpg",
//       "release_date": "1995-10-06",
//       "title": "Assassins",
//       "video": false,
//       "vote_average": 6.5,
//       "vote_count": 1538
//     },
//     {
//       "adult": false,
//       "backdrop_path": "/geSFMwnkHcRoiMPkwjWKMaP7NbY.jpg",
//       "genre_ids": [16, 35, 10751, 14],
//       "id": 220845,
//       "original_language": "en",
//       "original_title": "The Smurfs: The Legend of Smurfy Hollow",
//       "overview": "When Brainy Smurf is favored to win the annual Smurfberry Hunt for the ninth year in a row, Gutsy Smurf sets out to discover how Brainy wins every year. Gutsy’s investigation takes him into spooky Smurfy Hollow–and right into Gargamel’s trap! Can Brainy and Gutsy, with the help of Smurfette, put aside their rivalry before Gargamel captures them–or worse, they come face-to-face with the legendary ghost, the Headless Horseman?",
//       "popularity": 12.971,
//       "poster_path": "/AgFkdZawIUFY20rLRX9ejQtn0q2.jpg",
//       "release_date": "2013-09-12",
//       "title": "The Smurfs: The Legend of Smurfy Hollow",
//       "video": false,
//       "vote_average": 6.8,
//       "vote_count": 99
//     }
//   ]
